PDV/Models/ErrorViewModel.cs
using System;

namespace PDV.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PDV/Controllers/EstoqueController.cs
using System.Diagnostics;
using System.Linq;
using Dados;
using Microsoft.AspNetCore.Mvc;
using PDV.Models;

namespace PDV.Controllers
{
    public class EstoqueController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EstoqueController(ApplicationDbContext context)
        {
           _context = context;
        }

        [HttpGet]
        public IActionResult Estoque()
        {
            var produtos = _context.Produtos.ToList();

            return View(produtos);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PDV/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Logging;
using PDV.Models;

namespace PDV.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PDV/Controllers/ProdutoController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Dados;
using Dominio.Entidades;
using Microsoft.AspNetCore.Mvc;
using PDV.Models;

namespace PDV.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProdutoController(ApplicationDbContext context)
        {
           _context = context;
        }

        [HttpGet]
        public IActionResult Produto()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Produto(Produto produtos)
        {
            if(produtos.Id ==0){
            _context.Produtos.Add(produtos);
            }
            else {
                var produto = _context.Produtos.First(p => p.Id == produtos.Id);
                produto.Nome = produtos.Nome;
                produto.Quantidade = produtos.Quantidade;
                produto.ValorUnitario = produtos.ValorUnitario;
            }
            await _context.SaveChangesAsync();
            return Redirect("https://localhost:5001/Estoque/Estoque");
             
        }

        public IActionResult Editar(int id)
        {
            var produto = _context.Produtos.First(p => p.Id == id);
            return View("Produto",produto);
        }

        public async Task<IActionResult> Excluir(int id)
        {
            var produto = _context.Produtos.First(p => p.Id == id);
            _context.Produtos.Remove(produto);
            await _context.SaveChangesAsync();

            return Redirect("https://localhost:5001/Estoque/Estoque");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PDV/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Dados;
using Dominio.Entidades;
using Microsoft.AspNetCore.Mvc;
using PDV.Models;

namespace PDV.Controllers
{
    public class VendaController : Controller
    {
        
        private readonly ApplicationDbContext _context;

        public VendaController(ApplicationDbContext context)
        {
           _context = context;
        }

        public IActionResult Venda()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Venda(Venda venda){
            venda.dataVenda = DateTime.Now;
            _context.Add(venda);
            await _context.SaveChangesAsync();
            return Redirect("https://localhost:5001/Venda/Venda");
        }

        [HttpPost]
        public async Task<IActionResult> ItensVenda(ItensVendas itemvenda){
            
            var Codigo = _context.Vendas.Max( v => v.Id);
            Codigo = Codigo +1;
            itemvenda.CodigoVenda = Codigo;
            _context.ItensVendas.Add(itemvenda);
            await _context.SaveChangesAsync();
            return Redirect("https://localhost:5001/Venda/Venda");
        }

        public Task<IActionResult> Compra(int Id){
            var itemVenda = _context.ItensVendas.ToList(in => i.CodigoVenda = Id);
            return itemVenda;
        }

        public int Codigo()
        {
            var Codigo = _context.Vendas.Max( v => v.Id);
            Codigo = Codigo +1;
            return Codigo;
        }

        [HttpGet]
        public IActionResult Buscar(int id)
        {
            var Codigo = _context.Vendas.Max( v => v.Id);
            Codigo = Codigo +1;
            var itens = _context.ItensVendas.Where( i => i.CodigoVenda == Codigo);
            return View(itens.ToList());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PDV/Views/Estoque/Estoque.cshtml
@model IEnumerable<Dominio.Entidades.Produto>
@{
  Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/estoque.css">
    <script src="https://kit.fontawesome.com/d6011287c4.js" crossorigin="anonymous"></script>
    <title>Estoque</title>
</head>
<body>
    <div id="menu">
        <i class="fas fa-user-circle fa-lg" id="user"></i><span>   Usuario</span>
    </div>  
    <div id="menula">
        <ul id="itemMenu">
          <li id="menulaLi">
            <a asp-controller="Venda" asp-action="Venda" style="color: black;">
              <i class="fas fa-money-check-alt fa-lg" id="venda" title="Venda"></i>
            </a>     
          </li>
          <li id="menulaLi">
            <a asp-controller="Estoque" asp-action="Estoque" style="color: black;">
              <i class="fas fa-truck-loading fa-lg" id="estoque" title="Estoque"></i>
            </a>
          </li>
        </ul>
    </div>
    <div id="informacaoEstoque">
      <a asp-controller="Produto" asp-action="Produto"><button type="button" class="btn btn-secondary" id="addProd" >
        <i class="fas fa-plus fa-sm"></i>  Adicionar produto</button></a>
      <table style="width:80%" id="cabecalhoProd">
          <thead>
            <tr id="cabeçalho">
              <th>Código</th>
              <th>Produto</th>
              <th>Valor unitário</th>
              <th>Quantidade</th>
              <th>Opções</th>
            </tr>
          </thead>
          <tbody>
            @foreach (var item in Model)
            {
                <tr>
                  <td>@item.Id</td>
                  <td>@item.Nome</td>
                  <td >@item.ValorUnitario</td>
                  <td>@item.Quantidade</td>
                  <td>
                   <a href="/Produto/Editar/@item.Id"><i class="fas fa-pencil-alt" title="Editar"> </i></a>
                   <a href="/Produto/Excluir/@item.Id" id="trash"><i class="fas fa-trash-alt" title="Excluir" id="trash"></i></a>
                  </td>
                </tr>
            }
          </tbody>
    </div>
</body>
</html>

PDV/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/login.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <title>PDV</title>
</head>
<body style="background-color: dodgerblue;">
    <div class="login">
        <label id="titulo">Sistema de vendas</label>
        <br>
        <label id="login">Login</label>
        <br>
        <input type="text" maxlength="20" placeholder="Login">
        <br>
        <label id="senha">Senha</label>
        <br>
        <input type="password" id="password" maxlength="20" placeholder="Senha">
        <br>
        <br>
        <a class="nav-link text-dark" asp-area="" asp-controller="Venda" asp-action="Venda"><button type="button" class="btn btn-primary">Login</button></a>
    </div>
</body>
</html>

PDV/Views/Produto/Produto.cshtml
@model Dominio.Entidades.Produto
@{
  Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/produto.css">
    <script src="https://kit.fontawesome.com/d6011287c4.js" crossorigin="anonymous"></script>
    <title>Estoque</title>
</head>
<body>
    <div id="menu">
        <i class="fas fa-user-circle fa-lg" id="user"></i><span>   Usuario</span>
    </div>  
    <div id="menula">
        <ul id="itemMenu">
          <li id="menulaLi">
            <a asp-controller="Venda" asp-action="Venda" style="color: black;">
              <i class="fas fa-money-check-alt fa-lg" id="venda" title="Venda"></i>
            </a>     
          </li>
          <li id="menulaLi">
            <a asp-controller="Estoque" asp-action="Estoque" style="color: black;">
              <i class="fas fa-truck-loading fa-lg" id="estoque" title="Estoque"></i>
            </a>
          </li>
        </ul>
    </div>  
    <div id="main">
      <form asp-action="Produto" asp-controller="Produto" method="POST">
        <div>
            <input type="hidden" class="form-control" asp-for="Id"></input>             
            <label for="Nome">Nome</label>
            <input type="text" asp-for="Nome" required></input>
            <label for="Quantidade">Quantidade</label>
            <input type="number" asp-for="Quantidade" required> </input>
            <label for="ValorUnitario">Valor unitário (R$)</label>
            <input type="number" placeholder="0,00"  asp-for="ValorUnitario" required> </input>
        </div>

        <div id="mainfooter">
            <button class="btn btn-primary">Salvar</button>
            <button class="btn btn-secondary" onclick="history.go(-1)">Voltar</button>
        </div>
      </form>
    </div>
</body>
</html>

PDV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PDV</title>
    <link rel="stylesheet" href="~/wwwroot/css/login.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
</head>
<body style="background-color: dodgerblue;">
        
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PDV - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PDV/Views/Venda/Venda.cshtml
@model Dominio.Entidades.CompraViewModel
@{
  Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preload" href="~/css/index.css">
    <link rel="stylesheet" href="~/css/index.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <script src="https://kit.fontawesome.com/d6011287c4.js" crossorigin="anonymous"></script>
    <title>PDV</title>
</head>
<body>
    <div id="menu">
        <i class="fas fa-user-circle fa-lg" id="user"></i><span>  Usuario</span>
    </div>
    <div id="menula">
      <ul id="itemMenu">
        <li id="menulaLi">
          <a asp-area="" asp-controller="Venda" asp-action="Venda" style="color: black;">
            <i class="fas fa-money-check-alt fa-lg" id="venda" title="Venda"></i>
          </a>     
        </li>
        <li id="menulaLi">
          <a asp-area="" asp-controller="Estoque" asp-action="Estoque" style="color: black;">
            <i class="fas fa-truck-loading fa-lg" id="estoque" title="Estoque"></i>
          </a>
        </li>
      </ul>
  </div>
    <div id="telaVenda">    
      <form asp-action="ItensVenda" asp-controller="Venda" method="POST"> 
      <div id="prod">
      <p>Código do produto</p>
      <div class="input-group mb-3" >
        <input type="text" id="codProd" asp-for ="Item">
          <button class="btn btn-outline-secondary" asp-action="Buscar" asp-controller="Venda" type="button" id="codSearch"><i class="fas fa-search"></i></button>
      </div>
      <div>
        <ul id="InfoProd">
          <li id="infoProd">
            <p id="Qtd">Quantidade</p>
            <input type="number" id="qtd" asp-for ="Quantidade">
          </li>
          <li id="infoProd">
            <p style="text-align: left; margin-left: 10px;">Valor unitário</p>
            <input type="Number" id="valorUni" asp-for ="ValorUnitario">
          </li>
          <li id="infoProd">
            <p style="text-align: left; margin-left: 10px;">Valor Total</p>
            <input type="text" onfocus="valorTotal()" id="valorTot">
          </li>
        </ul>
        <br>
        <button class="btn btn-primary" id="add">Adicionar item</button>
      </div>
      <div id="listaProd" cols="30" rows="10">
          @Html.Partial("_ItensCompra")
      </div>
      </form>
    </div>  

    <button type="button" class="btn btn-success" id="buy" onclick="openModal('dv-modal')">Finalizar compra</button>
    <button type="button" class="btn btn-danger" id="cancel">Cancelar compra</button>

    <div id="dv-modal" class="modal">
      <form asp-action="Venda" asp-controller="Venda" method="POST"> 
      <div class="modal-content">
          <div class="modal-header">
              <h1>Pagamento</h1>
          </div>

          <div class="modal-body">
              <label>Valor Total (R$)</label>
              <input type="number" placeholder="0,00" asp-for = "ValorTotal" id="total"> </input>             
              <label>Forma de Pagamento</label>
              <select asp-for = "FormaPagamento">
                <option value="Dinheiro">Dinheiro</option>
                <option value="Card">Cartão de crédito</option>
                <option value="Debit card">Cartão de débito</option>
                <option value="Check">Cheque</option>
              </select>
              <label>Parcelas</label>
              <input type="number" placeholder="0,00" asp-for ="Parcelas"> </input>
              <label>Valor Recebido (R$)</label>
              <input type="number" placeholder="0,00" id="recebido"> </input>
              <label>Troco (R$)</label>
              <input type="text" placeholder="0,00" id="troco" onfocus="CalcTroco()"> </input>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" onclick="closeModal('dv-modal')">Voltar</button>
              <button class="btn btn-primary">Concluir</button>
          </div>
          </form>
      </div>
  </div>

  <script src="~/js/script.js"></script>
      

  </body>
</html>

PDV/Views/Venda/_ItensCompra.cshtml
@model IEnumerable <Dominio.Entidades.ItensVendas>
<table style="width:80%" id="cabecalhoProd">
    <thead>
        <tr id="cabeçalho">
            <th>Código</th>
            <th>Valor unitário</th>
            <th>Quantidade</th>
            <th>Valor Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.CodigoVenda</td>
                <td>@item.Item</td>
                <td>@item.ValorUnitario</td>
                <td>@item.Quantidade</td>
            </tr>
        }
    </tbody>
</table>